/* Generated By:JavaCC: Do not edit this line. JavaCCParserTokenManager.java */
package jminusminus;
import java.util.ArrayList;

public class JavaCCParserTokenManager implements JavaCCParserConstants
{
  public  java.io.PrintStream debugStream = System.out;
  public  void setDebugStream(java.io.PrintStream ds) { debugStream = ds; }
private final int jjStopStringLiteralDfa_0(int pos, long active0)
{
   switch (pos)
   {
      case 0:
         if ((active0 & 0x3fffffff80L) != 0L)
         {
            jjmatchedKind = 60;
            return 7;
         }
         if ((active0 & 0x800000000000000L) != 0L)
            return 102;
         return -1;
      case 1:
         if ((active0 & 0x3ffffdff80L) != 0L)
         {
            jjmatchedKind = 60;
            jjmatchedPos = 1;
            return 7;
         }
         if ((active0 & 0x20000L) != 0L)
            return 7;
         return -1;
      case 2:
         if ((active0 & 0x1fff1dff80L) != 0L)
         {
            if (jjmatchedPos != 2)
            {
               jjmatchedKind = 60;
               jjmatchedPos = 2;
            }
            return 7;
         }
         if ((active0 & 0x2000e00000L) != 0L)
            return 7;
         return -1;
      case 3:
         if ((active0 & 0x34fe1ded80L) != 0L)
         {
            jjmatchedKind = 60;
            jjmatchedPos = 3;
            return 7;
         }
         if ((active0 & 0xb01001200L) != 0L)
            return 7;
         return -1;
      case 4:
         if ((active0 & 0x247e1c2980L) != 0L)
         {
            jjmatchedKind = 60;
            jjmatchedPos = 4;
            return 7;
         }
         if ((active0 & 0x108001c400L) != 0L)
            return 7;
         return -1;
      case 5:
         if ((active0 & 0x200e182180L) != 0L)
         {
            jjmatchedKind = 60;
            jjmatchedPos = 5;
            return 7;
         }
         if ((active0 & 0x470040800L) != 0L)
            return 7;
         return -1;
      case 6:
         if ((active0 & 0x2008180080L) != 0L)
         {
            jjmatchedKind = 60;
            jjmatchedPos = 6;
            return 7;
         }
         if ((active0 & 0x6002100L) != 0L)
            return 7;
         return -1;
      case 7:
         if ((active0 & 0x2008180000L) != 0L)
         {
            jjmatchedKind = 60;
            jjmatchedPos = 7;
            return 7;
         }
         if ((active0 & 0x80L) != 0L)
            return 7;
         return -1;
      case 8:
         if ((active0 & 0x2008000000L) != 0L)
            return 7;
         if ((active0 & 0x180000L) != 0L)
         {
            jjmatchedKind = 60;
            jjmatchedPos = 8;
            return 7;
         }
         return -1;
      default :
         return -1;
   }
}
private final int jjStartNfa_0(int pos, long active0)
{
   return jjMoveNfa_0(jjStopStringLiteralDfa_0(pos, active0), pos + 1);
}
private final int jjStopAtPos(int pos, int kind)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   return pos + 1;
}
private final int jjStartNfaWithStates_0(int pos, int kind, int state)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) { return pos + 1; }
   return jjMoveNfa_0(state, pos + 1);
}
private final int jjMoveStringLiteralDfa0_0()
{
   switch(curChar)
   {
      case 33:
         return jjStopAtPos(0, 46);
      case 38:
         return jjMoveStringLiteralDfa1_0(0x100000000000L);
      case 40:
         return jjStopAtPos(0, 50);
      case 41:
         return jjStopAtPos(0, 51);
      case 42:
         return jjStopAtPos(0, 49);
      case 43:
         jjmatchedKind = 38;
         return jjMoveStringLiteralDfa1_0(0x1080000000000L);
      case 44:
         return jjStopAtPos(0, 58);
      case 45:
         jjmatchedKind = 47;
         return jjMoveStringLiteralDfa1_0(0x10000000000L);
      case 46:
         return jjStartNfaWithStates_0(0, 59, 102);
      case 58:
         return jjStopAtPos(0, 57);
      case 59:
         return jjStopAtPos(0, 56);
      case 60:
         return jjMoveStringLiteralDfa1_0(0x200000000000L);
      case 61:
         jjmatchedKind = 39;
         return jjMoveStringLiteralDfa1_0(0x20000000000L);
      case 62:
         return jjStopAtPos(0, 42);
      case 91:
         return jjStopAtPos(0, 54);
      case 93:
         return jjStopAtPos(0, 55);
      case 97:
         return jjMoveStringLiteralDfa1_0(0x80L);
      case 98:
         return jjMoveStringLiteralDfa1_0(0x100L);
      case 99:
         return jjMoveStringLiteralDfa1_0(0x600L);
      case 100:
         return jjMoveStringLiteralDfa1_0(0x800L);
      case 101:
         return jjMoveStringLiteralDfa1_0(0x3000L);
      case 102:
         return jjMoveStringLiteralDfa1_0(0x81c000L);
      case 105:
         return jjMoveStringLiteralDfa1_0(0x20003e0000L);
      case 110:
         return jjMoveStringLiteralDfa1_0(0x1400000L);
      case 112:
         return jjMoveStringLiteralDfa1_0(0x1e000000L);
      case 114:
         return jjMoveStringLiteralDfa1_0(0x20000000L);
      case 115:
         return jjMoveStringLiteralDfa1_0(0xc0000000L);
      case 116:
         return jjMoveStringLiteralDfa1_0(0x700000000L);
      case 118:
         return jjMoveStringLiteralDfa1_0(0x800000000L);
      case 119:
         return jjMoveStringLiteralDfa1_0(0x1000000000L);
      case 123:
         return jjStopAtPos(0, 52);
      case 125:
         return jjStopAtPos(0, 53);
      default :
         return jjMoveNfa_0(5, 0);
   }
}
private final int jjMoveStringLiteralDfa1_0(long active0)
{
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(0, active0);
      return 1;
   }
   switch(curChar)
   {
      case 38:
         if ((active0 & 0x100000000000L) != 0L)
            return jjStopAtPos(1, 44);
         break;
      case 43:
         if ((active0 & 0x80000000000L) != 0L)
            return jjStopAtPos(1, 43);
         break;
      case 45:
         if ((active0 & 0x10000000000L) != 0L)
            return jjStopAtPos(1, 40);
         break;
      case 61:
         if ((active0 & 0x20000000000L) != 0L)
            return jjStopAtPos(1, 41);
         else if ((active0 & 0x200000000000L) != 0L)
            return jjStopAtPos(1, 45);
         else if ((active0 & 0x1000000000000L) != 0L)
            return jjStopAtPos(1, 48);
         break;
      case 97:
         return jjMoveStringLiteralDfa2_0(active0, 0x2008000L);
      case 98:
         return jjMoveStringLiteralDfa2_0(active0, 0x80L);
      case 101:
         return jjMoveStringLiteralDfa2_0(active0, 0x20400000L);
      case 102:
         if ((active0 & 0x20000L) != 0L)
            return jjStartNfaWithStates_0(1, 17, 7);
         break;
      case 104:
         return jjMoveStringLiteralDfa2_0(active0, 0x1500000200L);
      case 105:
         return jjMoveStringLiteralDfa2_0(active0, 0x4000L);
      case 108:
         return jjMoveStringLiteralDfa2_0(active0, 0x11400L);
      case 109:
         return jjMoveStringLiteralDfa2_0(active0, 0xc0000L);
      case 110:
         return jjMoveStringLiteralDfa2_0(active0, 0x2000300000L);
      case 111:
         return jjMoveStringLiteralDfa2_0(active0, 0x800800900L);
      case 114:
         return jjMoveStringLiteralDfa2_0(active0, 0x20c000000L);
      case 116:
         return jjMoveStringLiteralDfa2_0(active0, 0x40000000L);
      case 117:
         return jjMoveStringLiteralDfa2_0(active0, 0x91000000L);
      case 120:
         return jjMoveStringLiteralDfa2_0(active0, 0x2000L);
      default :
         break;
   }
   return jjStartNfa_0(0, active0);
}
private final int jjMoveStringLiteralDfa2_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(0, old0); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(1, active0);
      return 2;
   }
   switch(curChar)
   {
      case 97:
         return jjMoveStringLiteralDfa3_0(active0, 0x40000600L);
      case 98:
         return jjMoveStringLiteralDfa3_0(active0, 0x10000000L);
      case 99:
         return jjMoveStringLiteralDfa3_0(active0, 0x2000000L);
      case 105:
         return jjMoveStringLiteralDfa3_0(active0, 0x1904000000L);
      case 108:
         return jjMoveStringLiteralDfa3_0(active0, 0x1008000L);
      case 110:
         return jjMoveStringLiteralDfa3_0(active0, 0x4000L);
      case 111:
         return jjMoveStringLiteralDfa3_0(active0, 0x8010100L);
      case 112:
         return jjMoveStringLiteralDfa3_0(active0, 0x800c0000L);
      case 114:
         if ((active0 & 0x800000L) != 0L)
            return jjStartNfaWithStates_0(2, 23, 7);
         return jjMoveStringLiteralDfa3_0(active0, 0x400000000L);
      case 115:
         return jjMoveStringLiteralDfa3_0(active0, 0x101080L);
      case 116:
         if ((active0 & 0x200000L) != 0L)
         {
            jjmatchedKind = 21;
            jjmatchedPos = 2;
         }
         return jjMoveStringLiteralDfa3_0(active0, 0x2020002000L);
      case 117:
         return jjMoveStringLiteralDfa3_0(active0, 0x200000800L);
      case 119:
         if ((active0 & 0x400000L) != 0L)
            return jjStartNfaWithStates_0(2, 22, 7);
         break;
      default :
         break;
   }
   return jjStartNfa_0(1, active0);
}
private final int jjMoveStringLiteralDfa3_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(1, old0); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(2, active0);
      return 3;
   }
   switch(curChar)
   {
      case 97:
         return jjMoveStringLiteralDfa4_0(active0, 0x14000L);
      case 98:
         return jjMoveStringLiteralDfa4_0(active0, 0x800L);
      case 100:
         if ((active0 & 0x800000000L) != 0L)
            return jjStartNfaWithStates_0(3, 35, 7);
         break;
      case 101:
         if ((active0 & 0x1000L) != 0L)
            return jjStartNfaWithStates_0(3, 12, 7);
         else if ((active0 & 0x200000000L) != 0L)
            return jjStartNfaWithStates_0(3, 33, 7);
         return jjMoveStringLiteralDfa4_0(active0, 0x2080002000L);
      case 107:
         return jjMoveStringLiteralDfa4_0(active0, 0x2000000L);
      case 108:
         if ((active0 & 0x1000000L) != 0L)
            return jjStartNfaWithStates_0(3, 24, 7);
         return jjMoveStringLiteralDfa4_0(active0, 0x1010080100L);
      case 111:
         return jjMoveStringLiteralDfa4_0(active0, 0x400040000L);
      case 114:
         if ((active0 & 0x200L) != 0L)
            return jjStartNfaWithStates_0(3, 9, 7);
         break;
      case 115:
         if ((active0 & 0x100000000L) != 0L)
            return jjStartNfaWithStates_0(3, 32, 7);
         return jjMoveStringLiteralDfa4_0(active0, 0x8400L);
      case 116:
         return jjMoveStringLiteralDfa4_0(active0, 0x48100080L);
      case 117:
         return jjMoveStringLiteralDfa4_0(active0, 0x20000000L);
      case 118:
         return jjMoveStringLiteralDfa4_0(active0, 0x4000000L);
      default :
         break;
   }
   return jjStartNfa_0(2, active0);
}
private final int jjMoveStringLiteralDfa4_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(2, old0); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(3, active0);
      return 4;
   }
   switch(curChar)
   {
      case 97:
         return jjMoveStringLiteralDfa5_0(active0, 0x6100000L);
      case 101:
         if ((active0 & 0x8000L) != 0L)
            return jjStartNfaWithStates_0(4, 15, 7);
         else if ((active0 & 0x1000000000L) != 0L)
            return jjStartNfaWithStates_0(4, 36, 7);
         return jjMoveStringLiteralDfa5_0(active0, 0x8080100L);
      case 105:
         return jjMoveStringLiteralDfa5_0(active0, 0x50000000L);
      case 108:
         if ((active0 & 0x4000L) != 0L)
            return jjStartNfaWithStates_0(4, 14, 7);
         return jjMoveStringLiteralDfa5_0(active0, 0x800L);
      case 110:
         return jjMoveStringLiteralDfa5_0(active0, 0x2000L);
      case 114:
         if ((active0 & 0x80000000L) != 0L)
            return jjStartNfaWithStates_0(4, 31, 7);
         return jjMoveStringLiteralDfa5_0(active0, 0x2020040080L);
      case 115:
         if ((active0 & 0x400L) != 0L)
            return jjStartNfaWithStates_0(4, 10, 7);
         break;
      case 116:
         if ((active0 & 0x10000L) != 0L)
            return jjStartNfaWithStates_0(4, 16, 7);
         break;
      case 119:
         return jjMoveStringLiteralDfa5_0(active0, 0x400000000L);
      default :
         break;
   }
   return jjStartNfa_0(3, active0);
}
private final int jjMoveStringLiteralDfa5_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(3, old0); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(4, active0);
      return 5;
   }
   switch(curChar)
   {
      case 97:
         return jjMoveStringLiteralDfa6_0(active0, 0x180L);
      case 99:
         if ((active0 & 0x10000000L) != 0L)
            return jjStartNfaWithStates_0(5, 28, 7);
         else if ((active0 & 0x40000000L) != 0L)
            return jjStartNfaWithStates_0(5, 30, 7);
         return jjMoveStringLiteralDfa6_0(active0, 0x8000000L);
      case 100:
         return jjMoveStringLiteralDfa6_0(active0, 0x2000L);
      case 101:
         if ((active0 & 0x800L) != 0L)
            return jjStartNfaWithStates_0(5, 11, 7);
         break;
      case 102:
         return jjMoveStringLiteralDfa6_0(active0, 0x2000000000L);
      case 103:
         return jjMoveStringLiteralDfa6_0(active0, 0x2000000L);
      case 109:
         return jjMoveStringLiteralDfa6_0(active0, 0x80000L);
      case 110:
         if ((active0 & 0x20000000L) != 0L)
            return jjStartNfaWithStates_0(5, 29, 7);
         return jjMoveStringLiteralDfa6_0(active0, 0x100000L);
      case 115:
         if ((active0 & 0x400000000L) != 0L)
            return jjStartNfaWithStates_0(5, 34, 7);
         break;
      case 116:
         if ((active0 & 0x40000L) != 0L)
            return jjStartNfaWithStates_0(5, 18, 7);
         return jjMoveStringLiteralDfa6_0(active0, 0x4000000L);
      default :
         break;
   }
   return jjStartNfa_0(4, active0);
}
private final int jjMoveStringLiteralDfa6_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(4, old0); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(5, active0);
      return 6;
   }
   switch(curChar)
   {
      case 97:
         return jjMoveStringLiteralDfa7_0(active0, 0x2000000000L);
      case 99:
         return jjMoveStringLiteralDfa7_0(active0, 0x100080L);
      case 101:
         if ((active0 & 0x2000000L) != 0L)
            return jjStartNfaWithStates_0(6, 25, 7);
         else if ((active0 & 0x4000000L) != 0L)
            return jjStartNfaWithStates_0(6, 26, 7);
         return jjMoveStringLiteralDfa7_0(active0, 0x80000L);
      case 110:
         if ((active0 & 0x100L) != 0L)
            return jjStartNfaWithStates_0(6, 8, 7);
         break;
      case 115:
         if ((active0 & 0x2000L) != 0L)
            return jjStartNfaWithStates_0(6, 13, 7);
         break;
      case 116:
         return jjMoveStringLiteralDfa7_0(active0, 0x8000000L);
      default :
         break;
   }
   return jjStartNfa_0(5, active0);
}
private final int jjMoveStringLiteralDfa7_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(5, old0); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(6, active0);
      return 7;
   }
   switch(curChar)
   {
      case 99:
         return jjMoveStringLiteralDfa8_0(active0, 0x2000000000L);
      case 101:
         return jjMoveStringLiteralDfa8_0(active0, 0x8100000L);
      case 110:
         return jjMoveStringLiteralDfa8_0(active0, 0x80000L);
      case 116:
         if ((active0 & 0x80L) != 0L)
            return jjStartNfaWithStates_0(7, 7, 7);
         break;
      default :
         break;
   }
   return jjStartNfa_0(6, active0);
}
private final int jjMoveStringLiteralDfa8_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(6, old0); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(7, active0);
      return 8;
   }
   switch(curChar)
   {
      case 100:
         if ((active0 & 0x8000000L) != 0L)
            return jjStartNfaWithStates_0(8, 27, 7);
         break;
      case 101:
         if ((active0 & 0x2000000000L) != 0L)
            return jjStartNfaWithStates_0(8, 37, 7);
         break;
      case 111:
         return jjMoveStringLiteralDfa9_0(active0, 0x100000L);
      case 116:
         return jjMoveStringLiteralDfa9_0(active0, 0x80000L);
      default :
         break;
   }
   return jjStartNfa_0(7, active0);
}
private final int jjMoveStringLiteralDfa9_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(7, old0); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(8, active0);
      return 9;
   }
   switch(curChar)
   {
      case 102:
         if ((active0 & 0x100000L) != 0L)
            return jjStartNfaWithStates_0(9, 20, 7);
         break;
      case 115:
         if ((active0 & 0x80000L) != 0L)
            return jjStartNfaWithStates_0(9, 19, 7);
         break;
      default :
         break;
   }
   return jjStartNfa_0(8, active0);
}
private final void jjCheckNAdd(int state)
{
   if (jjrounds[state] != jjround)
   {
      jjstateSet[jjnewStateCnt++] = state;
      jjrounds[state] = jjround;
   }
}
private final void jjAddStates(int start, int end)
{
   do {
      jjstateSet[jjnewStateCnt++] = jjnextStates[start];
   } while (start++ != end);
}
private final void jjCheckNAddTwoStates(int state1, int state2)
{
   jjCheckNAdd(state1);
   jjCheckNAdd(state2);
}
private final void jjCheckNAddStates(int start, int end)
{
   do {
      jjCheckNAdd(jjnextStates[start]);
   } while (start++ != end);
}
private final void jjCheckNAddStates(int start)
{
   jjCheckNAdd(jjnextStates[start]);
   jjCheckNAdd(jjnextStates[start + 1]);
}
static final long[] jjbitVec0 = {
   0x0L, 0x0L, 0xffffffffffffffffL, 0xffffffffffffffffL
};
private final int jjMoveNfa_0(int startState, int curPos)
{
   int[] nextStates;
   int startsAt = 0;
   jjnewStateCnt = 102;
   int i = 1;
   jjstateSet[0] = startState;
   int j, kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         MatchLoop: do
         {
            switch(jjstateSet[--i])
            {
               case 102:
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 74)
                        kind = 74;
                     jjCheckNAddStates(0, 2);
                  }
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(3, 5);
                  break;
               case 5:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(6, 21);
                  else if (curChar == 46)
                     jjCheckNAddTwoStates(22, 29);
                  else if (curChar == 34)
                     jjCheckNAddStates(22, 24);
                  else if (curChar == 39)
                     jjAddStates(25, 26);
                  else if (curChar == 36)
                  {
                     if (kind > 60)
                        kind = 60;
                     jjCheckNAdd(7);
                  }
                  else if (curChar == 47)
                     jjstateSet[jjnewStateCnt++] = 0;
                  if ((0x3fe000000000000L & l) != 0L)
                  {
                     if (kind > 71)
                        kind = 71;
                     jjCheckNAdd(10);
                  }
                  else if (curChar == 48)
                     jjAddStates(27, 38);
                  if (curChar == 48)
                  {
                     if (kind > 71)
                        kind = 71;
                  }
                  break;
               case 0:
                  if (curChar == 47)
                     jjCheckNAddStates(39, 41);
                  break;
               case 1:
                  if ((0xffffffffffffdbffL & l) != 0L)
                     jjCheckNAddStates(39, 41);
                  break;
               case 2:
                  if ((0x2400L & l) != 0L && kind > 6)
                     kind = 6;
                  break;
               case 3:
                  if (curChar == 10 && kind > 6)
                     kind = 6;
                  break;
               case 4:
                  if (curChar == 13)
                     jjstateSet[jjnewStateCnt++] = 3;
                  break;
               case 6:
                  if (curChar != 36)
                     break;
                  if (kind > 60)
                     kind = 60;
                  jjCheckNAdd(7);
                  break;
               case 7:
                  if ((0x3ff001000000000L & l) == 0L)
                     break;
                  if (kind > 60)
                     kind = 60;
                  jjCheckNAdd(7);
                  break;
               case 8:
                  if (curChar == 48 && kind > 71)
                     kind = 71;
                  break;
               case 9:
                  if ((0x3fe000000000000L & l) == 0L)
                     break;
                  if (kind > 71)
                     kind = 71;
                  jjCheckNAdd(10);
                  break;
               case 10:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 71)
                     kind = 71;
                  jjCheckNAdd(10);
                  break;
               case 11:
                  if (curChar == 39)
                     jjAddStates(25, 26);
                  break;
               case 13:
                  if ((0x8400000000L & l) != 0L)
                     jjCheckNAdd(14);
                  break;
               case 14:
                  if (curChar == 39 && kind > 72)
                     kind = 72;
                  break;
               case 15:
                  if ((0xffffff7fffffdbffL & l) != 0L)
                     jjCheckNAdd(14);
                  break;
               case 16:
                  if (curChar == 34)
                     jjCheckNAddStates(22, 24);
                  break;
               case 18:
                  if ((0x8400000000L & l) != 0L)
                     jjCheckNAddStates(22, 24);
                  break;
               case 19:
                  if ((0xfffffffbffffdbffL & l) != 0L)
                     jjCheckNAddStates(22, 24);
                  break;
               case 20:
                  if (curChar == 34 && kind > 78)
                     kind = 78;
                  break;
               case 21:
                  if (curChar == 46)
                     jjCheckNAddTwoStates(22, 29);
                  break;
               case 22:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(3, 5);
                  break;
               case 24:
                  if ((0x280000000000L & l) != 0L)
                     jjCheckNAddTwoStates(25, 27);
                  break;
               case 25:
                  if (curChar == 48)
                     jjCheckNAdd(26);
                  break;
               case 27:
                  if ((0x3fe000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(28, 26);
                  break;
               case 28:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(28, 26);
                  break;
               case 29:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 74)
                     kind = 74;
                  jjCheckNAddStates(0, 2);
                  break;
               case 31:
                  if ((0x280000000000L & l) != 0L)
                     jjCheckNAddTwoStates(32, 34);
                  break;
               case 32:
                  if (curChar != 48)
                     break;
                  if (kind > 74)
                     kind = 74;
                  jjCheckNAdd(33);
                  break;
               case 34:
                  if ((0x3fe000000000000L & l) == 0L)
                     break;
                  if (kind > 74)
                     kind = 74;
                  jjCheckNAddTwoStates(35, 33);
                  break;
               case 35:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 74)
                     kind = 74;
                  jjCheckNAddTwoStates(35, 33);
                  break;
               case 36:
                  if (curChar == 48)
                     jjAddStates(27, 38);
                  break;
               case 38:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(42, 45);
                  break;
               case 39:
                  if (curChar == 46)
                     jjCheckNAddTwoStates(40, 26);
                  break;
               case 41:
                  if ((0x280000000000L & l) != 0L)
                     jjCheckNAddTwoStates(25, 42);
                  break;
               case 42:
                  if ((0x3fe000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(43, 26);
                  break;
               case 43:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(43, 26);
                  break;
               case 46:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjAddStates(46, 47);
                  break;
               case 47:
                  if (curChar == 46)
                     jjCheckNAdd(48);
                  break;
               case 48:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(48, 50);
                  break;
               case 51:
                  if (curChar == 46)
                     jjCheckNAdd(52);
                  break;
               case 52:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(51, 53);
                  break;
               case 55:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 74)
                     kind = 74;
                  jjCheckNAddStates(54, 57);
                  break;
               case 56:
                  if (curChar != 46)
                     break;
                  if (kind > 74)
                     kind = 74;
                  jjCheckNAddTwoStates(57, 33);
                  break;
               case 58:
                  if ((0x280000000000L & l) != 0L)
                     jjCheckNAddTwoStates(32, 59);
                  break;
               case 59:
                  if ((0x3fe000000000000L & l) == 0L)
                     break;
                  if (kind > 74)
                     kind = 74;
                  jjCheckNAddTwoStates(60, 33);
                  break;
               case 60:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 74)
                     kind = 74;
                  jjCheckNAddTwoStates(60, 33);
                  break;
               case 63:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjAddStates(58, 59);
                  break;
               case 64:
                  if (curChar == 46)
                     jjCheckNAdd(65);
                  break;
               case 65:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 74)
                     kind = 74;
                  jjCheckNAddStates(60, 62);
                  break;
               case 68:
                  if (curChar == 46)
                     jjCheckNAdd(69);
                  break;
               case 69:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 74)
                     kind = 74;
                  jjCheckNAddStates(63, 65);
                  break;
               case 71:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(6, 21);
                  break;
               case 72:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(72, 73);
                  break;
               case 73:
                  if (curChar == 46)
                     jjCheckNAdd(26);
                  break;
               case 74:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(74, 75);
                  break;
               case 76:
                  if ((0x280000000000L & l) != 0L)
                     jjCheckNAddTwoStates(25, 77);
                  break;
               case 77:
                  if ((0x3fe000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(78, 26);
                  break;
               case 78:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(78, 26);
                  break;
               case 79:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(79, 80);
                  break;
               case 80:
                  if (curChar == 46)
                     jjCheckNAdd(81);
                  break;
               case 81:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(66, 68);
                  break;
               case 83:
                  if ((0x280000000000L & l) != 0L)
                     jjCheckNAddTwoStates(25, 84);
                  break;
               case 84:
                  if ((0x3fe000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(85, 26);
                  break;
               case 85:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(85, 26);
                  break;
               case 86:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(86, 26);
                  break;
               case 87:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(87, 88);
                  break;
               case 88:
                  if (curChar != 46)
                     break;
                  if (kind > 74)
                     kind = 74;
                  jjCheckNAdd(33);
                  break;
               case 89:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(89, 90);
                  break;
               case 91:
                  if ((0x280000000000L & l) != 0L)
                     jjCheckNAddTwoStates(32, 92);
                  break;
               case 92:
                  if ((0x3fe000000000000L & l) == 0L)
                     break;
                  if (kind > 74)
                     kind = 74;
                  jjCheckNAddTwoStates(93, 33);
                  break;
               case 93:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 74)
                     kind = 74;
                  jjCheckNAddTwoStates(93, 33);
                  break;
               case 94:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(94, 95);
                  break;
               case 95:
                  if (curChar == 46)
                     jjCheckNAdd(96);
                  break;
               case 96:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 74)
                     kind = 74;
                  jjCheckNAddStates(69, 71);
                  break;
               case 98:
                  if ((0x280000000000L & l) != 0L)
                     jjCheckNAddTwoStates(32, 99);
                  break;
               case 99:
                  if ((0x3fe000000000000L & l) == 0L)
                     break;
                  if (kind > 74)
                     kind = 74;
                  jjCheckNAddTwoStates(100, 33);
                  break;
               case 100:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 74)
                     kind = 74;
                  jjCheckNAddTwoStates(100, 33);
                  break;
               case 101:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(101, 33);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 077);
         MatchLoop: do
         {
            switch(jjstateSet[--i])
            {
               case 5:
               case 7:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 60)
                     kind = 60;
                  jjCheckNAdd(7);
                  break;
               case 1:
                  jjAddStates(39, 41);
                  break;
               case 12:
                  if (curChar == 92)
                     jjstateSet[jjnewStateCnt++] = 13;
                  break;
               case 13:
                  if ((0x14404410000000L & l) != 0L)
                     jjCheckNAdd(14);
                  break;
               case 15:
                  if ((0xffffffffefffffffL & l) != 0L)
                     jjCheckNAdd(14);
                  break;
               case 17:
                  if (curChar == 92)
                     jjstateSet[jjnewStateCnt++] = 18;
                  break;
               case 18:
                  if ((0x14404410000000L & l) != 0L)
                     jjCheckNAddStates(22, 24);
                  break;
               case 19:
                  if ((0xffffffffefffffffL & l) != 0L)
                     jjCheckNAddStates(22, 24);
                  break;
               case 23:
                  if ((0x2000000020L & l) != 0L)
                     jjCheckNAddStates(72, 74);
                  break;
               case 26:
                  if ((0x4000000040L & l) != 0L && kind > 73)
                     kind = 73;
                  break;
               case 30:
                  if ((0x2000000020L & l) != 0L)
                     jjCheckNAddStates(75, 77);
                  break;
               case 33:
                  if ((0x1000000010L & l) != 0L && kind > 74)
                     kind = 74;
                  break;
               case 37:
                  if (curChar == 120)
                     jjCheckNAdd(38);
                  break;
               case 38:
                  if ((0x7e0000007eL & l) != 0L)
                     jjCheckNAddStates(42, 45);
                  break;
               case 40:
                  if ((0x1000000010000L & l) != 0L)
                     jjCheckNAddStates(78, 80);
                  break;
               case 44:
                  if (curChar == 88)
                     jjCheckNAdd(38);
                  break;
               case 45:
                  if (curChar == 120)
                     jjCheckNAddTwoStates(46, 47);
                  break;
               case 46:
                  if ((0x7e0000007eL & l) != 0L)
                     jjCheckNAddTwoStates(46, 47);
                  break;
               case 48:
                  if ((0x7e0000007eL & l) != 0L)
                     jjCheckNAddStates(48, 50);
                  break;
               case 49:
                  if (curChar == 88)
                     jjCheckNAddTwoStates(46, 47);
                  break;
               case 50:
                  if (curChar == 120)
                     jjCheckNAdd(51);
                  break;
               case 52:
                  if ((0x7e0000007eL & l) != 0L)
                     jjCheckNAddStates(51, 53);
                  break;
               case 53:
                  if (curChar == 88)
                     jjCheckNAdd(51);
                  break;
               case 54:
                  if (curChar == 120)
                     jjCheckNAdd(55);
                  break;
               case 55:
                  if ((0x7e0000007eL & l) == 0L)
                     break;
                  if (kind > 74)
                     kind = 74;
                  jjCheckNAddStates(54, 57);
                  break;
               case 57:
                  if ((0x1000000010000L & l) != 0L)
                     jjCheckNAddStates(81, 83);
                  break;
               case 61:
                  if (curChar == 88)
                     jjCheckNAdd(55);
                  break;
               case 62:
                  if (curChar == 120)
                     jjCheckNAddTwoStates(63, 64);
                  break;
               case 63:
                  if ((0x7e0000007eL & l) != 0L)
                     jjCheckNAddTwoStates(63, 64);
                  break;
               case 65:
                  if ((0x7e0000007eL & l) == 0L)
                     break;
                  if (kind > 74)
                     kind = 74;
                  jjCheckNAddStates(60, 62);
                  break;
               case 66:
                  if (curChar == 88)
                     jjCheckNAddTwoStates(63, 64);
                  break;
               case 67:
                  if (curChar == 120)
                     jjCheckNAdd(68);
                  break;
               case 69:
                  if ((0x7e0000007eL & l) == 0L)
                     break;
                  if (kind > 74)
                     kind = 74;
                  jjCheckNAddStates(63, 65);
                  break;
               case 70:
                  if (curChar == 88)
                     jjCheckNAdd(68);
                  break;
               case 75:
                  if ((0x2000000020L & l) != 0L)
                     jjCheckNAddStates(84, 86);
                  break;
               case 82:
                  if ((0x2000000020L & l) != 0L)
                     jjCheckNAddStates(87, 89);
                  break;
               case 90:
                  if ((0x2000000020L & l) != 0L)
                     jjCheckNAddStates(90, 92);
                  break;
               case 97:
                  if ((0x2000000020L & l) != 0L)
                     jjCheckNAddStates(93, 95);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int i2 = (curChar & 0xff) >> 6;
         long l2 = 1L << (curChar & 077);
         MatchLoop: do
         {
            switch(jjstateSet[--i])
            {
               case 1:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     jjAddStates(39, 41);
                  break;
               case 15:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     jjstateSet[jjnewStateCnt++] = 14;
                  break;
               case 19:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     jjAddStates(22, 24);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      if ((i = jjnewStateCnt) == (startsAt = 102 - (jjnewStateCnt = startsAt)))
         return curPos;
      try { curChar = input_stream.readChar(); }
      catch(java.io.IOException e) { return curPos; }
   }
}
static final int[] jjnextStates = {
   29, 30, 33, 22, 23, 26, 72, 73, 74, 75, 79, 80, 86, 26, 87, 88, 
   89, 90, 94, 95, 101, 33, 17, 19, 20, 12, 15, 37, 44, 45, 49, 50, 
   53, 54, 61, 62, 66, 67, 70, 1, 2, 4, 38, 39, 40, 26, 46, 47, 
   48, 40, 26, 52, 40, 26, 55, 56, 57, 33, 63, 64, 65, 57, 33, 69, 
   57, 33, 81, 82, 26, 96, 97, 33, 24, 25, 27, 31, 32, 34, 41, 25, 
   42, 58, 32, 59, 76, 25, 77, 83, 25, 84, 91, 32, 92, 98, 32, 99, 
};
public static final String[] jjstrLiteralImages = {
"", null, null, null, null, null, null, "\141\142\163\164\162\141\143\164", 
"\142\157\157\154\145\141\156", "\143\150\141\162", "\143\154\141\163\163", "\144\157\165\142\154\145", 
"\145\154\163\145", "\145\170\164\145\156\144\163", "\146\151\156\141\154", 
"\146\141\154\163\145", "\146\154\157\141\164", "\151\146", "\151\155\160\157\162\164", 
"\151\155\160\154\145\155\145\156\164\163", "\151\156\163\164\141\156\143\145\157\146", "\151\156\164", "\156\145\167", 
"\146\157\162", "\156\165\154\154", "\160\141\143\153\141\147\145", 
"\160\162\151\166\141\164\145", "\160\162\157\164\145\143\164\145\144", "\160\165\142\154\151\143", 
"\162\145\164\165\162\156", "\163\164\141\164\151\143", "\163\165\160\145\162", "\164\150\151\163", 
"\164\162\165\145", "\164\150\162\157\167\163", "\166\157\151\144", "\167\150\151\154\145", 
"\151\156\164\145\162\146\141\143\145", "\53", "\75", "\55\55", "\75\75", "\76", "\53\53", "\46\46", "\74\75", "\41", 
"\55", "\53\75", "\52", "\50", "\51", "\173", "\175", "\133", "\135", "\73", "\72", 
"\54", "\56", null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, };
public static final String[] lexStateNames = {
   "DEFAULT", 
};
static final long[] jjtoToken = {
   0x1fffffffffffff81L, 0x14780L, 
};
static final long[] jjtoSkip = {
   0x7eL, 0x0L, 
};
protected SimpleCharStream input_stream;
private final int[] jjrounds = new int[102];
private final int[] jjstateSet = new int[204];
protected char curChar;
public JavaCCParserTokenManager(SimpleCharStream stream){
   if (SimpleCharStream.staticFlag)
      throw new Error("ERROR: Cannot use a static CharStream class with a non-static lexical analyzer.");
   input_stream = stream;
}
public JavaCCParserTokenManager(SimpleCharStream stream, int lexState){
   this(stream);
   SwitchTo(lexState);
}
public void ReInit(SimpleCharStream stream)
{
   jjmatchedPos = jjnewStateCnt = 0;
   curLexState = defaultLexState;
   input_stream = stream;
   ReInitRounds();
}
private final void ReInitRounds()
{
   int i;
   jjround = 0x80000001;
   for (i = 102; i-- > 0;)
      jjrounds[i] = 0x80000000;
}
public void ReInit(SimpleCharStream stream, int lexState)
{
   ReInit(stream);
   SwitchTo(lexState);
}
public void SwitchTo(int lexState)
{
   if (lexState >= 1 || lexState < 0)
      throw new TokenMgrError("Error: Ignoring invalid lexical state : " + lexState + ". State unchanged.", TokenMgrError.INVALID_LEXICAL_STATE);
   else
      curLexState = lexState;
}

protected Token jjFillToken()
{
   Token t = Token.newToken(jjmatchedKind);
   t.kind = jjmatchedKind;
   String im = jjstrLiteralImages[jjmatchedKind];
   t.image = (im == null) ? input_stream.GetImage() : im;
   t.beginLine = input_stream.getBeginLine();
   t.beginColumn = input_stream.getBeginColumn();
   t.endLine = input_stream.getEndLine();
   t.endColumn = input_stream.getEndColumn();
   return t;
}

int curLexState = 0;
int defaultLexState = 0;
int jjnewStateCnt;
int jjround;
int jjmatchedPos;
int jjmatchedKind;

public Token getNextToken() 
{
  int kind;
  Token specialToken = null;
  Token matchedToken;
  int curPos = 0;

  EOFLoop :
  for (;;)
  {   
   try   
   {     
      curChar = input_stream.BeginToken();
   }     
   catch(java.io.IOException e)
   {        
      jjmatchedKind = 0;
      matchedToken = jjFillToken();
      return matchedToken;
   }

   try { input_stream.backup(0);
      while (curChar <= 32 && (0x100003600L & (1L << curChar)) != 0L)
         curChar = input_stream.BeginToken();
   }
   catch (java.io.IOException e1) { continue EOFLoop; }
   jjmatchedKind = 0x7fffffff;
   jjmatchedPos = 0;
   curPos = jjMoveStringLiteralDfa0_0();
   if (jjmatchedPos == 0 && jjmatchedKind > 80)
   {
      jjmatchedKind = 80;
   }
   if (jjmatchedKind != 0x7fffffff)
   {
      if (jjmatchedPos + 1 < curPos)
         input_stream.backup(curPos - jjmatchedPos - 1);
      if ((jjtoToken[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
      {
         matchedToken = jjFillToken();
         return matchedToken;
      }
      else
      {
         continue EOFLoop;
      }
   }
   int error_line = input_stream.getEndLine();
   int error_column = input_stream.getEndColumn();
   String error_after = null;
   boolean EOFSeen = false;
   try { input_stream.readChar(); input_stream.backup(1); }
   catch (java.io.IOException e1) {
      EOFSeen = true;
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
      if (curChar == '\n' || curChar == '\r') {
         error_line++;
         error_column = 0;
      }
      else
         error_column++;
   }
   if (!EOFSeen) {
      input_stream.backup(1);
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
   }
   throw new TokenMgrError(EOFSeen, curLexState, error_line, error_column, error_after, curChar, TokenMgrError.LEXICAL_ERROR);
  }
}

}
