/* Generated By:JavaCC: Do not edit this line. JavaCCParserConstants.java */
package jminusminus;

public interface JavaCCParserConstants {

  int EOF = 0;
  int SINGLE_LINE_COMMENT = 6;
  int ABSTRACT = 7;
  int BOOLEAN = 8;
  int CHAR = 9;
  int CLASS = 10;
  int DOUBLE = 11;
  int ELSE = 12;
  int EXTENDS = 13;
  int FINAL = 14;
  int FALSE = 15;
  int FLOAT = 16;
  int IF = 17;
  int IMPORT = 18;
  int IMPLEMENTS = 19;
  int INSTANCEOF = 20;
  int INT = 21;
  int NEW = 22;
  int FOR = 23;
  int NULL = 24;
  int PACKAGE = 25;
  int PRIVATE = 26;
  int PROTECTED = 27;
  int PUBLIC = 28;
  int RETURN = 29;
  int STATIC = 30;
  int SUPER = 31;
  int THIS = 32;
  int TRUE = 33;
  int THROWS = 34;
  int VOID = 35;
  int WHILE = 36;
  int INTERFACE = 37;
  int PLUS = 38;
  int ASSIGN = 39;
  int DEC = 40;
  int EQUAL = 41;
  int GT = 42;
  int INC = 43;
  int LAND = 44;
  int LE = 45;
  int LNOT = 46;
  int MINUS = 47;
  int PLUS_ASSIGN = 48;
  int STAR = 49;
  int LPAREN = 50;
  int RPAREN = 51;
  int LCURLY = 52;
  int RCURLY = 53;
  int LBRACK = 54;
  int RBRACK = 55;
  int SEMI = 56;
  int COL = 57;
  int COMMA = 58;
  int DOT = 59;
  int IDENTIFIER = 60;
  int LETTER = 61;
  int DIGIT = 62;
  int DIGITS = 63;
  int NON_ZERO_DIGIT = 64;
  int HEX_DIGIT = 65;
  int HEX_DIGITS = 66;
  int HEX_NUMERAL = 67;
  int HEX_SIGNIFICANT = 68;
  int BINARY_EXPONENT = 69;
  int EXPONENT_PART = 70;
  int INT_LITERAL = 71;
  int CHAR_LITERAL = 72;
  int FLOAT_LITERAL = 73;
  int DOUBLE_LITERAL = 74;
  int FLOATING_POINT_LITERAL = 75;
  int DECIMAL_FLOATING_POINT = 76;
  int HEXADECIMAL_FLOATING_POINT = 77;
  int STRING_LITERAL = 78;
  int ESC = 79;
  int ERROR = 80;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<SINGLE_LINE_COMMENT>",
    "\"abstract\"",
    "\"boolean\"",
    "\"char\"",
    "\"class\"",
    "\"double\"",
    "\"else\"",
    "\"extends\"",
    "\"final\"",
    "\"false\"",
    "\"float\"",
    "\"if\"",
    "\"import\"",
    "\"implements\"",
    "\"instanceof\"",
    "\"int\"",
    "\"new\"",
    "\"for\"",
    "\"null\"",
    "\"package\"",
    "\"private\"",
    "\"protected\"",
    "\"public\"",
    "\"return\"",
    "\"static\"",
    "\"super\"",
    "\"this\"",
    "\"true\"",
    "\"throws\"",
    "\"void\"",
    "\"while\"",
    "\"interface\"",
    "\"+\"",
    "\"=\"",
    "\"--\"",
    "\"==\"",
    "\">\"",
    "\"++\"",
    "\"&&\"",
    "\"<=\"",
    "\"!\"",
    "\"-\"",
    "\"+=\"",
    "\"*\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\":\"",
    "\",\"",
    "\".\"",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "<DIGITS>",
    "<NON_ZERO_DIGIT>",
    "<HEX_DIGIT>",
    "<HEX_DIGITS>",
    "<HEX_NUMERAL>",
    "<HEX_SIGNIFICANT>",
    "<BINARY_EXPONENT>",
    "<EXPONENT_PART>",
    "<INT_LITERAL>",
    "<CHAR_LITERAL>",
    "<FLOAT_LITERAL>",
    "<DOUBLE_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<DECIMAL_FLOATING_POINT>",
    "<HEXADECIMAL_FLOATING_POINT>",
    "<STRING_LITERAL>",
    "<ESC>",
    "<ERROR>",
  };

}
